// Canvas Schema Types - AI ROI & Roadmap Canvas

export interface CanvasHeader {
  canvasTitle: string;
  name: string;
  designedBy: string;
  designedFor: string;
  date: string;
  version: string;
}

export interface CanvasObjectives {
  primaryGoal: string;
  strategicFocus: string[];
}

export interface CanvasInputs {
  resources: string[];
  personnel: string[];
  externalSupport: string[];
}

export interface CanvasImpacts {
  hardBenefits: string[];
  softBenefits: string[];
}

export interface Milestone {
  name: string;
  date: string;
  description: string;
}

export interface TimelineItem {
  aiInitiative: string;
  startDate: string;
  endDate: string;
  milestones: Milestone[];
  timeframe: 'Q1' | '1-Year' | '3-Year';
}

export interface Risk {
  name: string;
  likelihood: 'Low' | 'Medium' | 'High';
  impact: 'Low' | 'Medium' | 'High';
  mitigation: string;
}

export interface CanvasCapabilities {
  skillsNeeded: string[];
  technology: string[];
}

export interface CanvasCosts {
  nearTerm: number;
  longTerm: number;
  annualMaintenance: number;
}

export interface CanvasBenefits {
  nearTerm: number;
  longTerm: number;
  softBenefits: string[];
}

export interface PortfolioROI {
  nearTermROIPercent: number;
  longTermROIPercent: number;
  portfolioNote: string;
}

export interface CanvasFooter {
  creditLine: string;
}

// Main Canvas Type combining all sections
export interface AIROICanvas {
  header: CanvasHeader;
  objectives: CanvasObjectives;
  inputs: CanvasInputs;
  impacts: CanvasImpacts;
  timeline: TimelineItem[];
  risks: Risk[];
  capabilities: CanvasCapabilities;
  costs: CanvasCosts;
  benefits: CanvasBenefits;
  portfolioROI: PortfolioROI;
  footer: CanvasFooter;
}

// AI Use Case type for the interview flow
export interface AIUseCase {
  id: string;
  name: string;
  problemStatement: string;
  kpis: string[];
  hardBenefits: number; // Annual $ value
  softBenefits: string[];
  implementationCost: number;
  annualCost: number;
  effortScore: 1 | 2 | 3 | 4 | 5; // 1 = Low, 5 = High
  impactScore: 1 | 2 | 3 | 4 | 5; // 1 = Low, 5 = High
  riskLevel: 'Low' | 'Medium' | 'High';
  dependencies: string[];
  timeframe: 'Q1' | '1-Year' | '3-Year';
  selected: boolean;
}

// ROI Calculation Results
export interface ROICalculation {
  useCaseId: string;
  basicROI: number; // (Benefit - Cost) / Cost as percentage
  npv: number; // Net Present Value at 10%
  paybackPeriod: number; // In months
  riskAdjustedValue: number;
}

// Chat Message types
export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: Date;
}

// Interview State
export type InterviewPhase = 
  | 'welcome'
  | 'company-context'
  | 'use-case-capture'
  | 'roi-review'
  | 'portfolio-selection'
  | 'roadmap-generation'
  | 'canvas-export'
  | 'complete';

// Default empty canvas
export const createEmptyCanvas = (): AIROICanvas => ({
  header: {
    canvasTitle: 'AI ROI & Roadmap Canvas',
    name: '',
    designedBy: '',
    designedFor: '',
    date: new Date().toISOString().split('T')[0],
    version: '1.0',
  },
  objectives: {
    primaryGoal: '',
    strategicFocus: [],
  },
  inputs: {
    resources: [],
    personnel: [],
    externalSupport: [],
  },
  impacts: {
    hardBenefits: [],
    softBenefits: [],
  },
  timeline: [],
  risks: [],
  capabilities: {
    skillsNeeded: [],
    technology: [],
  },
  costs: {
    nearTerm: 0,
    longTerm: 0,
    annualMaintenance: 0,
  },
  benefits: {
    nearTerm: 0,
    longTerm: 0,
    softBenefits: [],
  },
  portfolioROI: {
    nearTermROIPercent: 0,
    longTermROIPercent: 0,
    portfolioNote: '',
  },
  footer: {
    creditLine: 'Generated by AI ROI Canvas Agent',
  },
});

// Default empty use case
export const createEmptyUseCase = (id: string): AIUseCase => ({
  id,
  name: '',
  problemStatement: '',
  kpis: [],
  hardBenefits: 0,
  softBenefits: [],
  implementationCost: 0,
  annualCost: 0,
  effortScore: 3,
  impactScore: 3,
  riskLevel: 'Medium',
  dependencies: [],
  timeframe: '1-Year',
  selected: false,
});

